version: '2.1'
services: 

  database:
    image: mysql
    container_name: nodejs_mysql
    command: mysqld --user=root --verbose
    volumes:
      - /apps/docker/mysql:/var/lib/mysql
      - ./mysql/db_crud_nodejs.sql:/tmp/dbsetup.sql
      - ./mysql/importdb.sh:/tmp/importdb.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db_crud_nodejs"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks: 
      apinetwork:
  web:
    build: .
    container_name: noderest
    command: npm start
    #volumes:
     # - .:/usr/src/app
    ports:
      - "8000:8000"
    networks: 
      apinetwork:

networks:
  apinetwork:
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
          aux_addreses:
            database: 172.16.238.2 
# ipam is removed in version 3, issues with swarm mode
# https://github.com/docker/compose/issues/4474     